### ISSUE TITLE
Range Slider - Possible bug

### ISSUE THREAD

**Issue by pta19059** [foex-open-source/fos-range-slider#3]
Good Morning,
Can you please consider the doc attached (with a test case) and let us know if we have encountered a bug and provide us help?

Thanks in advance for the support.

Stefano

[FOS Range Slider - Bug.docx](https://github.com/foex-open-source/fos-range-slider/files/9157811/FOS.Range.Slider.-.Bug.docx)

**Comment by pta19059** [comment]
@foex-open-source Can I get an update please? Best Regards Stefano

**Comment by foex-open-source** [comment]
Hi Stefano!
We couldn't reproduce the described behavior, so can you please create a test case on apex.oracle.com and provide access details so we can investigate your issue. 
Thanks

**Comment by pta19059** [comment]
Hi @foex-open-source . You can mark the issue closed. We didn't realized that there was the event Range slider change. Thanks for the support!
